package io.github.shiyioo.thymeleafreactive

import org.springframework.boot.autoconfigure.AutoConfiguration
import org.springframework.boot.context.properties.EnableConfigurationProperties

@AutoConfiguration
@EnableConfigurationProperties(ReactiveProperties::class)
class ReactiveAutoConfiguration
